export default function MenuButton(props: any) {
  return (
    <button 
      type="button" 
      className="
        w-1/5
        text-white-900 
        hover:text-white 
        border 
        border-neutral-800 
        hover:bg-stone-900 
        focus:ring-4 
        focus:outline-none 
        focus:ring-stone-300 
        font-medium 
        rounded-lg 
        text-sm 
        px-5 
        py-2.5 
        text-center 
        mb-1
        dark:border-stone-600 
        dark:text-stone-400 
        dark:hover:text-white 
        dark:hover:bg-stone-600 
        dark:focus:ring-stone-800"
      onClick={props.onClick}>
    {props.text}
    </button>
  ); 
}
